title: 英语单词整理
description: 人教版小学、初中、高中及四六级、专四、专八英语单词表，含英式/美式音标、英文例句和中文翻译。
markdown: kramdown

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - README.md

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - scripts
  - .idea
  - .DS_Store
  - __pycache__
  - "*.pyc"
